### ISSUE TITLE
venting issue

### ISSUE THREAD

**Issue by Racpy** [AaronMcKenney/ttt2-role_impo#2]
when player venting, if the time expires, this error will be thrown.
![image](https://github.com/AaronMcKenney/ttt2-role_impo/assets/59442552/73e049ef-57ee-4347-a544-294e3eff00ae)

**Comment by AaronMcKenney** [comment]
Hey Racpy. I'm not quite able to reproduce this on my end. It's possible that there's a race condition going on, perhaps due to lag? Could you share more details on how you obtained this error?

I just made a code change that could fix this issue for you (commit below). Could you check?
https://github.com/AaronMcKenney/ttt2-role_impo/commit/c8c9900df3c1c7bc6b60d4cdf3c3a9506546dad7

**Comment by Racpy** [comment]
> Hey Racpy. I'm not quite able to reproduce this on my end. It's possible that there's a race condition going on, perhaps due to lag? Could you share more details on how you obtained this error?
> 
> I just made a code change that could fix this issue for you (commit below). Could you check? [c8c9900](https://github.com/AaronMcKenney/ttt2-role_impo/commit/c8c9900df3c1c7bc6b60d4cdf3c3a9506546dad7)

Yes, it is fixed, but the timer only works for the first 30 seconds.
when 30 seconds expires it throws me out of the vent, after which there is no longer a 30 second limit on vent entry.
![image](https://github.com/AaronMcKenney/ttt2-role_impo/assets/59442552/f11dd7df-99c3-4321-83c9-36e4d2db17f7)

**Comment by AaronMcKenney** [comment]
Are you a Trapper role (I've been assuming that you were this whole time)? Because that's how it works if you're the trapper, since the trapper is an innocent subrole. If they were allowed permanent entry into a vent they could just sit there and win the game, hence the time limit.

Your screenshot is of the Impostor though, which should be unrelated, especially since the green status icon on the left does not have a number that ticks down. A quick test on my end shows that the code for them is working just fine: They can stay in the vent for as long as they'd like.

If you are a plain old impostor, and you are being shoved out of a vent after 30 seconds, then I'll need a fair bit of information from you, such as: The steps you perform to repeat the issue (a video here would be appreciated), Impostor ConVars that are different from default values, any addons that may be causing conflicts, etc.

**Comment by Racpy** [comment]
> Are you a Trapper role (I've been assuming that you were this whole time)? Because that's how it works if you're the trapper, since the trapper is an innocent subrole. If they were allowed permanent entry into a vent they could just sit there and win the game, hence the time limit.
> 
> Your screenshot is of the Impostor though, which should be unrelated, especially since the green status icon on the left does not have a number that ticks down. A quick test on my end shows that the code for them is working just fine: They can stay in the vent for as long as they'd like.
> 
> If you are a plain old impostor, and you are being shoved out of a vent after 30 seconds, then I'll need a fair bit of information from you, such as: The steps you perform to repeat the issue (a video here would be appreciated), Impostor ConVars that are different from default values, any addons that may be causing conflicts, etc.

well, I think I misunderstood the introduction of this role, but IMPOSTER didn't required install the Trapper role in the steam workshop.
![image](https://github.com/AaronMcKenney/ttt2-role_impo/assets/59442552/cf6750ad-71f1-456d-b03c-330317c6bd43)

so, vent time is only apply on Trapper role, right?

I will install Trapper role later to test again.

**Comment by Racpy** [comment]
here is test video as imposter with https://github.com/AaronMcKenney/ttt2-role_impo/commit/c8c9900df3c1c7bc6b60d4cdf3c3a9506546dad7 (no trapper role now)

mstack warn non-traitor message also show when imposter venting too.

https://github.com/AaronMcKenney/ttt2-role_impo/assets/59442552/f134f8cb-4db3-4b35-8300-51b6fa92d3f6

**Comment by AaronMcKenney** [comment]
The Trapper thing is a small feature I added for fun, to make the Trapper more interesting. To be honest, I don't think anyone really uses this feature, I just added it for kicks. For some reason you're entering this logic though despite being an Impostor, and I have no idea why. I will have to delve a bit deeper into the code. It could be that you have a conflicting addon, but I have no idea. Perhaps there's some extra guard I can put into place...

**Comment by Racpy** [comment]
> The Trapper thing is a small feature I added for fun, to make the Trapper more interesting. To be honest, I don't think anyone really uses this feature, I just added it for kicks. For some reason you're entering this logic though despite being an Impostor, and I have no idea why. I will have to delve a bit deeper into the code. It could be that you have a conflicting addon, but I have no idea. Perhaps there's some extra guard I can put into place...


Got it, after installing trapper everything was fine.
This is my addons collection: https://steamcommunity.com/sharedfiles/filedetails/?id=3001672099
I think there should be no addons causing conflicts.

**Comment by AaronMcKenney** [comment]
Figured it out. The issue was that if the Trapper wasn't installed ROLE_TRAPPER would be nil, which caused issues when I compared it in an if statement.

Thanks for the catch. Bit weird that you're the first to point out this issue. I think it's been around since the Impostor was initially released?
