### ISSUE TITLE
sabotage comms mstack spam 

### ISSUE THREAD

**Issue by Racpy** [AaronMcKenney/ttt2-role_impo#4]
sometimes when start sabotage comms will spam "An Impostor has sabotaged the comms!"
what actually happened is uncertain. It's possible that sabotage comms started while the player was talking.

need to rejoin server to solved it.

**Comment by AaronMcKenney** [comment]
Hello, thanks for reporting the issue, and apologies for the delay on my end. Yes, I may have been a bit excessive with that message, which will (for example) be sent whenever the client hits the push-to-talk key. It'll also be sent whenever the client attempts to send a chat message or a ttt_radio command. The reasoning for this was to simply make it evident that the lack of communication is due to the Impostor specifically, as opposed to some issue with the client's computer or network connection.

There's a few ways I can go about fixing it. I suppose the simplest way is to simply get rid of the message altogether since the role already has a pop-up message for it when the sabotage begins. I haven't played TTT2 in a couple years now, so I think you might actually have more experience with this role then myself. Which is to say that I'm open to suggestions.

**Comment by Racpy** [comment]
> Hello, thanks for reporting the issue, and apologies for the delay on my end. Yes, I may have been a bit excessive with that message, which will (for example) be sent whenever the client hits the push-to-talk key. It'll also be sent whenever the client attempts to send a chat message or a ttt_radio command. The reasoning for this was to simply make it evident that the lack of communication is due to the Impostor specifically, as opposed to some issue with the client's computer or network connection.
> 
> There's a few ways I can go about fixing it. I suppose the simplest way is to simply get rid of the message altogether since the role already has a pop-up message for it when the sabotage begins. I haven't played TTT2 in a couple years now, so I think you might actually have more experience with this role then myself. Which is to say that I'm open to suggestions.

Thanks for your reply, it usually works fine, I'm just not sure if it's pressing the talk button too many times after starting sabotage comms, or if it's a bug causing the spam, because the spam usually still exists after 5~10 minutes, so I have to reconnect.

I discussed with my friends that if the bug is serious and difficult to fix, they would be fine with removing the mstack_warn when trying to send voice or text after starting sabotage comms. I agree that removing mstack_warn is the easiest way, because mstack_warn is not as obvious as EPOP:AddMessage, it is easier to ignore and not notice.

**Comment by Racpy** [comment]
I found the VOD from the past few days, and the link has been set to the time it happened.
[twitch vod](https://www.twitch.tv/videos/2160894186?t=02h34m15s)

time continues to 02:37:10 until I reconnect, still spamming mstack_warn.

**Comment by AaronMcKenney** [comment]
Ok. The issue should be fixed now. I got rid of the MSTACK message for attempting to use voice chat during sabo comms. In addition, if the player attempts to use text chat during sabo comms, the message will be sent to chat instead of MSTACK.

I also went ahead and pushed it to official, and I'll close this issue with this comment, since it's pretty straightforward IMO. But feel free to reopen the issue if you still see this issue.
